[project]
name = "log-analyzer"
version = "0.1.0"
description = "Анализатор журналов ngnix"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "pytest>=9.0.3",
    "ruff>=0.15.15",
    "structlog>=25.5.0",
    "tqdm>=4.67.3",
]

[tool.ruff]
line-length = 150
target-version = "py313"
src = ["src"]

[tool.ruff.lint]
select = [
    "E",    # ошибки
    "W",    # предупреждения
    "F",    # неиспользуемые импорты/переменные
    "I",    # сортировка импортов
    "UP",   # современный синтаксис
]

ignore = [
    "UP035",  # Отключил упоминание deprecated Dict
    "UP006",  # Отключил упоминание Use `dict` instead of `Dict` for type annotation
    "UP015",  # Отключил что mode указывать не нужно при открытии файла
    "I001"    # Отключил упоминания об некорректных импортах

]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.pytest.ini_options]
minversion = "9.0"
testpaths = ["tests"]
addopts = "-v"
log_cli = false
log_file = "app-logs/test.log"
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true # Отключение маскирования кириллицы

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.15",
]
